### ISSUE TITLE
discussion: modeling servers at a high level

### ISSUE THREAD

**Issue by cakekindel** [toad-lib/toad#128]
There are a few higher-level server/resource abstractions that would be useful and include different shades of effort to implement, document, and understand as a user.

## Considerations
|priority|consideration|explain|
|--|--|--|
|high|barrier to entry (protocol)|it should be easy to pick up and use CoAP without having to read any RFCs|
|high|barrier to entry (API)|it should be easy to pick up and get a kwap server running without having to read a book|
|med|boilerplate|it should be low-code|
|med|goof-proof|it should be hard to fuck things up|
|med|unopinionated|the library shouldn't make it hard to do things that weren't expressly considered by the authors (me)|
|low|effort to implement|it should be easy to implement these abstractions|

## Potential solutions
 - **As-Is** leave the medium-level "middleware" abstraction and defer the complexity to users (and open up the opportunity for a higher-level abstraction to the OSS community)
 - **Traits** `kwap` provides `App` and `Resource` traits that use the type system to fill in default behavior
 - **Concretes** `kwap` provides hard structures `App`, `Resource` with builder APIs
 - **Proc Macros** a la rocket
 
### As-Is
|how it does|consideration|explain|
|--|--|--|
|:star::small_orange_diamond::small_orange_diamond::small_orange_diamond::small_orange_diamond:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|barrier to entry (protocol)|you have to know a lot about CoAP to write and read this|
|:star::small_orange_diamond::small_orange_diamond::small_orange_diamond::small_orange_diamond:|barrier to entry (API)|you have to read a lot of docs to understand what to do|
|:star::star::small_orange_diamond::small_orange_diamond::small_orange_diamond:|boilerplate|it's not low-code but is simple to reason about if you have enough context to read and write it|
|:star::small_orange_diamond::small_orange_diamond::small_orange_diamond::small_orange_diamond:|goof-proof|this is hard to look at, read, write, and debug|
|:star::star::star::star::star:|unopinionated|this is about as unopinionated as it gets -- make me some bread; here's flour, sugar, yeast, and water.|
|:star::star::star::star::star:|effort to implement|super easy, this already exists! :smile:|
```rust
mod counter {
  static mut COUNTER: Option<Mutex<u64>> = None;

  fn init() {
    unsafe {COUNTER = Some(Mutex::new(0));}
  }

  fn read() -> u64 {
    unsafe {COUNTER.unwrap().lock().unwrap()}
  }

  fn incr() {
    unsafe {COUNTER.unwrap().lock() += 1;}
  }
}

fn get_counter(req: Req) -> (Continue, Action) {
  match (req.method(), req.path()) {
    (Method::GET, "counter") => {
      let mut resp = Resp::for_request(req).unwrap();
      resp.set_payload(counter::read().to_be_bytes());
      (Continue::No, Action::Send(resp))
    },
    _ => (Continue::No, /* 4.04 */)
  }
}

fn main() {
 let mut server = Server::try_new().unwrap();
}
```

### Traits
|how it does|consideration|explain|
|--|--|--|
|:star::star::star::star::small_orange_diamond:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|barrier to entry (protocol)|this uses the type system to convert RESTful ideas and thinking into real code|
|:star::star::star::small_orange_diamond::small_orange_diamond:|barrier to entry (API)|this isn't terribly complex and uses the type system in a mildly novel way to model restful ideas|
|:star::star::star::small_orange_diamond::small_orange_diamond:|boilerplate|definitely boilerplate-heavy. The fact that matching a request to a resource needs to be a function for every resource is an example of a mild amount of friction that this adds|
|:star::star::star::star::star:|goof-proof|encourages sound, safe code that follows the coap spec every time|
|:star::star::small_orange_diamond::small_orange_diamond::small_orange_diamond:|unopinionated|slightly more opinionated but still open-ended|
|:star::star::star::small_orange_diamond::small_orange_diamond:|effort to implement|medium|
```rust
struct CounterResource;
struct CounterApp {
  counter: u64,
}

impl App for CounterApp {}

impl Resource<CounterApp> for CounterResource {
  fn matches(&self, method: Method, path: &str) -> bool {
    method == GET && path == "counter"
  }
  
  fn respond(&self, app: &mut CounterApp, req: Req<P>) -> Resp<P> {
    let mut resp = Resp::for_req(req).unwrap();
    resp.set_payload_json(app.data_stream);
    app.count += 1;
    resp
  }
}

CounterApp {counter: 0}.serve();
```

### Builder model
|how it does|consideration|explain|
|--|--|--|
|:star::star::star::star::small_orange_diamond:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|barrier to entry (protocol)|The API guides you down a path of success and understanding|
|:star::star::star::star::star:|barrier to entry (API)|Very low, the builder pattern should be very familiar even to greener rust users|
|:star::star::star::small_orange_diamond::small_orange_diamond:|boilerplate|Definitely more boilerplate than the trait solution, but personally I feel that the declarative nature of builders makes it a bit more ergonomic and readable|
|:star::star::star::star::star:|goof-proof|The API guides you down a path of success and makes state management extremely easy|
|:star::star::star::small_orange_diamond::small_orange_diamond:|unopinionated|this model is pretty extensible and open|
|:star::star::star::small_orange_diamond::small_orange_diamond:|effort to implement|Somewhat low effort to implement (maybe a bit more than the previous)|
```rust
let counter = Resource::builder()
                       .route("/counter")
                       .method(GET)
                       .state(|| 0u32)
                       .handle_with_state_lock(|count, req| {
                         let mut resp = Resp::for_request(req).unwrap();
                         resp.set_payload(count);
                         count += 1;
                         Ok(resp)
                       })
                       .build()
                       .unwrap();

let app = App::builder()
              .resource(counter)
              .build()
              .unwrap()
              .serve(5463);
```

### Proc Macro
|how it does|consideration|explain|
|--|--|--|
|:star::star::star::star::small_orange_diamond:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|barrier to entry (protocol)|The API guides you down a path of success and understanding|
|:star::star::star::star::small_orange_diamond:|barrier to entry (API)|Very low, but more than the builder pattern because the syntax within the macro invocation is totally bespoke|
|:star::star::star::star::star:|boilerplate|Borderline no-code solution|
|:star::star::star::star::star:|goof-proof|The API guides you down a path of success and makes state management extremely easy|
|:star::star::star::small_orange_diamond::small_orange_diamond:|unopinionated|this model is pretty extensible and open|
|:star::small_orange_diamond::small_orange_diamond::small_orange_diamond::small_orange_diamond:|effort to implement|Most effort to implement|
```rust
#[get("/counter", state(0u32, lock = true))]
fn counter(count: u32, req: Req) -> Resp {
  let mut resp = Resp::for_request(req).unwrap();
  resp.set_payload(count);
  count += 1;
  resp
}

#[go]
fn kwap_main() {
  kwap::go(routes![counter])
}
```

**Comment by cakekindel** [comment]
todo: after reading this i feel like the first one is much more boilerplate-heavy than the second

**Comment by chrysn** [comment]
You might want to have a look at how `coap-handler` models these, with the main example at https://gitlab.com/chrysn/coap-message-demos/-/blob/master/src/lib.rs (due disclosure: it's a shameless plug of libraries I'm maintaining).

It may be lacking a few features (because it aims to be a highly generic interface, describing common ground between many CoAP stacks), but might be practical input to this thread's considerations.

**Comment by cakekindel** [comment]
thanks for your input! i drew a lot of inspiration from your work around coap - since writing this I've been leaning heavily towards the macro attribute style a la Rocket for the sake of approachability and UX
